### ISSUE TITLE
CRITICAL: Possible to move() CarTransport and Scania while ramp is in wrong position. 

### ISSUE THREAD

**Issue by ArthurAlexandersson** [Knodeln/TDA553-lab1#11]
It's currently possible to call move() on trucks when their platform is in wrong position. Possible solution: override move() and add an extra condition before calling super.move().

**Comment by Knodeln** [comment]
What do you mean? The method increment speed is overridden in the subclass TruckWithFlatbed, both which CarTransporter and Scania inherit from. The test in both testclasses can_move_while_flatbed_not_fastened covers this.

**Comment by ArthurAlexandersson** [comment]
Yes that is correct, sorry about that. I added a new Critical Issue, please have a look at that.
