### ISSUE TITLE
Labreflection

### ISSUE THREAD

**Issue by ArthurAlexandersson** [Knodeln/TDA553-lab1#12]
What is the contract for gas() and brake()? If you were to override the gas() and brake() method in TruckWithFlatbed, and then adding an extra condition before calling super.gas()/super.brake() (e.g. checking if the platform is in the correct position in order to call gas() on a Truck with platform), would that still adhere to the LSP?  
https://github.com/Knodeln/TDA553-lab1/blob/cd252a7880da6d09a010a1e063947a1be4359930/lab2reflection.txt#L3

**Comment by Knodeln** [comment]
This will indeed break the contract since objects of the superclass might not have the flatbedfastened attribute. Should we implement a gas and break for every type of vehicle subclass?

**Comment by ArthurAlexandersson** [comment]
This would indeed violate the LSP, by strengthening the contract for gas/brake. However, that is in some cases fine, as long as you understand why these changes would violate the LSP.

**Comment by ArthurAlexandersson** [comment]
And no you should not make implement a gas/brake for every type of vehicle subclass.
Only for those where it's necessary, i.e. for trucks with platforms

**Comment by Knodeln** [comment]
I see, then I will keep it as it is and keep it in mind in the future.
