### ISSUE TITLE
CRITICAL: Have a look at incrementSpeed, decrementSpeed and setCurrentSpeed 

### ISSUE THREAD

**Issue by ArthurAlexandersson** [Knodeln/TDA553-lab1#13]
Move can't be called while the ramp is in the wrong position. 
However, it's better to make increment/decrement-speed private and move them to vehicle. Since they're public now, and no condition which checks if the input is valid, calling decrementSpeed(-10) will set currentSpeed to 7, which violates the sanity checks from lab1, calling incrementSpeed(10) also sets speed to 7. Making these two methods private would also mean that setCurrentSpeed() could be made private, which also, currently, can be used to violate the sanity checks from lab1. 
If you don't want to make them private, another possible solution would be to add an extra condtion which checks that the input is valid (within the allowed range, see lab1). For all of those methods, however it's better to make them private and only have the input check in gas and brake.

**Comment by Knodeln** [comment]
Made the inc/dec speed methods protected since they should be overridden when you have a flatbed.

**Comment by ArthurAlexandersson** [comment]
The methods can still be called from those objects which could still violate the sanity checks, unless an extra condition is added. 
But making them private would still be a better option, since the condition you'll want to add is already in gas() and brake(). And instead of overriding inc/dec speed you'd want to override gas(), brake() and startEngine() and adding a condition which checks if the platform is in the correct position before calling the super method. 
e.g. `@Override gas(amount){if(isFlatbedFastened) { super.gas(amount);}`

**Comment by Knodeln** [comment]
Overrode turnOnEngine and gas and made inc/dec speed private. Lower and raise flatbed now requires is isEngineOn to be false and speed to be 0
