### ISSUE TITLE
CRITICAL: Possible to load and unload CarTransport when platform up or down. 

### ISSUE THREAD

**Issue by ArthurAlexandersson** [Knodeln/TDA553-lab1#8]
There's currently no condition which is checked before loading or unloading if the ramp is up or down. 
https://github.com/Knodeln/TDA553-lab1/blob/cd252a7880da6d09a010a1e063947a1be4359930/src/Cartransporter.java#L17-L19

**Comment by Knodeln** [comment]
added if statement (getSpeed == 0)

**Comment by ArthurAlexandersson** [comment]
That will not solve the issue, you'll have to check the platform' state before loading/unloading

**Comment by Knodeln** [comment]
Added isFlatbedFastened (getter for FlatbedFastened)

**Comment by Knodeln** [comment]
Now can't start engine if flatbed is lowered and can't lower ramp if engine is on
